---
apiVersion: v1
kind: Service
metadata:
  name: website-example
  labels:
    app: website-example
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: website-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-example
  template:
    metadata:
      labels:
        app: website-example
    spec:
      containers:
        - name: website-example
          image: koderover.tencentcloudcr.com/koderover-demo/website-example:1.0.0
          ports:
            - containerPort: 80
