apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: registry
  name: registry
spec:
  ports:
  - name: http
    port: 8761
    targetPort: 8761
  selector:
    project: piggymetrics
    tier: infrastructure
    app: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: registry
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
     project: piggymetrics
     tier: infrastructure
     app: registry  
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: infrastructure
        app: registry
    spec:
      initContainers:
        - name: init-skywalking-agent
          image: koderover.tencentcloudcr.com/koderover-demo/skywalking-agent:8.8.0
          command:
            - 'sh'
            - '-c'
            - 'set -ex;mkdir -p /vmskywalking/agent;cp -r /usr/skywalking/agent/* /vmskywalking/agent;'
          volumeMounts:
            - mountPath: /vmskywalking/agent
              name: skywalking-agent
      containers:
      - env:
        - name: JAVA_OPTS
          value: "-javaagent:/opt/skywalking/agent/skywalking-agent.jar -Duser.timezone=GMT+8"
        - name: SW_AGENT_NAME
          value: "registry"
        - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
          value: "{{.oap_svc}}.skywalking.svc.cluster.local:11800"
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: config_service_password
        envFrom:
        - configMapRef:
           name: special-config-env
        image: koderover.tencentcloudcr.com/koderover-demo/piggymetrics-registry:v0.3.0
        name: registry
        resources:
          limits:
            cpu: 800m
            memory: 1G
          requests:
            cpu: 400m
            memory: 768M        
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
        volumeMounts:
          - mountPath: /opt/skywalking/agent
            name: skywalking-agent
      restartPolicy: Always
      volumes:
        - name: skywalking-agent
          emptyDir: {}
