apiVersion: v1
kind: Service
metadata:
  name: auth-mongodb
  labels:
    project: piggymetrics
    tier: database
    app: auth-mongodb
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    project: piggymetrics
    tier: database
    app: auth-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongodb
  labels:
    project: piggymetrics
    tier: database
    app: auth-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
     project: piggymetrics
     tier: database
     app: auth-mongodb 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: database
        app: auth-mongodb
    spec:
      containers:
      - image: koderover.tencentcloudcr.com/koderover-demo/piggymetrics-mongodb:v0.1.1
        name: auth-mongodb
        env:
          - name: MONGODB_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: piggymetrics
                key: auth_mongodb_password
        ports:
          - containerPort: 27017
        resources:
          limits:
            cpu: 500m
            memory: 1G
          requests:
            cpu: 100m
            memory: 256M
      restartPolicy: Always
